### ISSUE TITLE
Improve efficiency of threadpool/prime finding

### ISSUE THREAD

**Issue by rossica** [rossica/primebot#6]
The problem with the current model is that the std::function calls have quite a bit of overhead, however, it does shrink with the amount of work being done.

The std::async implementation has even more overhead, unfortunately. (std::async appears to create a lambda which then calls the std::function object it creates internally for the parameters passed in.

I think the solution is to either use C-style function pointers, for figure out how to get the template to inline the functions passed in. (can the compiler even inline another class's member-function into a template class's function?)

Also, test whether the OneLockThreadpool spends less time waiting on a lock than Threadpool does. The current profiling shows that the std::function overhead is still greater than the time spent waiting for the WorkItems lock, but once that is fixed, this is the next target.

**Comment by Alex-Kreitzberg** [comment]
`std::function` has a lot of overhead. The `async` input is templated I believe, so it should be possible for it to inline it. Replacing the prime range search with a lambda might actually make it faster (because it's implemented as a struct, and those inline). I'll see if I can find some indirections which can be optimized out.

The compiler can inline functions by way of the templates.

**Comment by rossica** [comment]
Have you used the VisualStudio CPU profiler? Its pretty spiffy!
 It seems the new async code you pushed last night spends about 8% of its time in the odd() calls. I'm still trying to understand how it all comes together, but couldn't odd() be implemented as a check for even and an addition of 1, instead of the multiplication then addition?

-----Original Message-----

**Comment by Alex-Kreitzberg** [comment]
I didn't know the cpu profiler existed! Odd was on my "worry list" an actual tool would be much better. 

I thought I would try an interface that mapped numbers to odd numbers to avoid checks and redundant bounds. I also figured the user wouldn't have to make sure there bounds were odd, or anything like that. 

I'm not sold on that decision,  I wanted to play with it to see how it felt, or if it was confusing.

**Comment by Alex-Kreitzberg** [comment]
odd makes the interface confusing,  and is very slow.  I'm removing it.

When using the profiler, the exclusive time in the callback call was really small. The Islikelyprime was hanging up in some way, the exclusive time was almost 1 percent.  So something funny is going on,  an unnecessary copy, conversion or something.

**Comment by Alex-Kreitzberg** [comment]
When compiled in Release it doesn't show the same overhead.

**Comment by rossica** [comment]
Like all the overhead disappears? or it's just different (hopefully less) than before?

**Comment by Alex-Kreitzberg** [comment]
There is almost no overhead I think,  if I'm reading this right.

**Comment by rossica** [comment]
I think you are reading it right; the self CPU% column is for the time spent in the function itself, not including it's callees.

-----Original Message-----

**Comment by rossica** [comment]
The only performance improvement I can think of at this point is to make the threadpool have an inlined thread function, but that doesn't seem necessary. I need to check the CPU profiler, but I'm almost certain that it optimizes to a function-pointer call.

**Comment by Alex-Kreitzberg** [comment]
You could probably get the templates to inline the thread properly, but configuring data members via the templates can get sort of hairy.

It's definitely an optimization that should be done with care.

**Comment by rossica** [comment]
I feel like this issue has reached about all the conclusions it will and am going to close it.
In the future, if testing reveals performance bottlenecks, it can be re-opened.
